export type TListing = {
  id: number,
  propertyTypeId?: number,
  name: string,
  externalListingName: string,
  internalListingName?: string,
  description?: string,
  thumbnailUrl?: string,
  houseRules?: string,
  keyPickup?: string,
  specialInstruction?: string,
  doorSecurityCode?: string,
  country?: string,
  countryCode?: string,
  state?: string,
  city?: string,
  street?: string,
  address: string,
  publicAddress?: string,
  zipcode?: string,
  price: number,
  starRating?: number,
  weeklyDiscount?: number,
  monthlyDiscount?: number,
  propertyRentTax?: number,
  guestPerPersonPerNightTax?: number,
  guestStayTax?: number,
  guestNightlyTax?: number,
  refundableDamageDeposit?: number,
  personCapacity?: number,
  maxChildrenAllowed?: number,
  maxInfantsAllowed?: number,
  maxPetsAllowed?: number,
  lat?: number,
  lng?: number,
  checkInTimeStart?: number,
  checkInTimeEnd?: number,
  checkOutTime?: number,
  cancellationPolicy?: string,
  cancellationPolicyId?: number,
  vrboCancellationPolicyId?: number,
  airBnbCancellationPolicyId?: number,
  marriottCancellationPolicyId?: number,
  bookingCancellationPolicyId?: number,
  squareMeters?: number,
  roomType?: string,
  bathroomType?: string,
  bedroomsNumber?: number,
  bedsNumber?: number,
  bedType?: string,
  bathroomsNumber?: number,
  minNights?: number,
  maxNights?: number,
  guestsIncluded: number,
  cleaningFee?: number,
  priceForExtraPerson: number,
  instantBookable?: number,
  instantBookableLeadTime?: number,
  allowSameDayBooking?: number,
  sameDayBookingLeadTime?: number,
  contactName?: string,
  contactSurName?: string,
  contactPhone1?: string,
  contactPhone2?: string,
  contactLanguage?: string,
  contactEmail?: string,
  contactAddress?: string,
  language?: string,
  currencyCode: string,
  timeZoneName?: string,
  wifiUsername?: string,
  wifiPassword?: string,
  cleannessStatus?: string,
  cleaningInstruction?: string,
  cleannessStatusUpdatedOn?: string | Date,
  homeawayPropertyName: string,
  homeawayPropertyHeadline?: string,
  homeawayPropertyDescription?: string,
  bookingcomPropertyName?: string,
  bookingcomPropertyDescription?: string,
  invoicingContactName?: string,
  invoicingContactSurName?: string,
  invoicingContactPhone1?: string,
  invoicingContactPhone2?: string,
  invoicingContactLanguage?: string,
  invoicingContactEmail?: string,
  invoicingContactAddress?: string,
  invoicingContactCity?: string,
  invoicingContactZipcode?: string,
  invoicingContactCountry?: string,
  propertyLicenseNumber?: string,
  propertyLicenseType?: string,
  propertyLicenseIssueDate?: string | Date,
  propertyLicenseExpirationDate?: string | Date,
  partnersListingMarkup?: number,
  isRentalAgreementActive?: boolean,
  listingAgreementText?: string,
  listingAmenities?: TListingAmenity[],
  listingBedTypes?: TListingBed[],
  listingImages?: TListingImage[],
  customFieldValues?: { customFieldId: number, value: string }[],
};

export type TListingAmenity = { id: number, amenityId: number };

export type TListingBed = { id: number, bedTypeId: number, quantity: number };

export type TListingImage = { id: number, caption?: string, url: string, sortOrder?: number };

//===========================================================================================================

export type TCalendar = {
  id: number,
  date: string | Date,
  isAvailable?: boolean | number,
  isProcessed?: boolean | number,
  status?: string,
  price?: number,
  minimumStay?: number,
  maximumStay?: number,
  closedOnArrival?: boolean | number,
  closedOnDeparture?: boolean | number,
  note?: string,
  countAvailableUnits?: number,
  availableUnitsToSell?: number,
  countPendingUnits?: number,
  countBlockingReservations?: number,
  countBlockedUnits?: number,
  desiredUnitsToSell?: number,
  reservations?: TReservation[],
};

export type TReservation = {
  id: number,
  listingMapId: number,
  channelId: number,
  source?: string,
  channelName: string,
  reservationId: string,
  externalPropertyId?: string,
  externalRatePlanId?: string,
  externalUnitId?: string,
  externalRuid?: string,
  manualIcalId?: string,
  manualIcalName?: string,
  isProcessed?: boolean | number,
  isManuallyChecked?: boolean | number,
  isInstantBooked?: boolean | number,
  hasPullError?: boolean | number,
  reservationDate?: string | Date,
  pendingExpireDate?: string | Date,
  guestName?: string,
  guestFirstName?: string,
  guestLastName?: string,
  guestExternalAccountId?: string,
  guestCity?: string,
  guestCountry?: string,
  guestEmail?: string,
  guestPicture?: string,
  numberOfGuests?: number,
  adults?: number,
  children?: number,
  infants?: number,
  pets?: number,
  arrivalDate: string | Date,
  departureDate: string | Date,
  previousArrivalDate?: string | Date,
  previousDepartureDate?: string | Date,
  checkInTime?: number,
  checkOutTime?: number,
  nights?: number,
  phone?: string,
  totalPrice?: number,
  taxAmount?: number,
  channelCommissionAmount?: number,
  hostawayCommissionAmount?: number,
  cleaningFee?: number,
  securityDepositFee?: number,
  isPaid?: boolean | number,
  paymentMethod?: string,
  stripeGuestId?: string,
  currency?: string,
  status?: string,
  hostNote?: string,
  guestNote?: string,
  comment?: string,
};
