/**
 * This file contains the data and logic to import initial BlogPost data into database
 * TODO: REMOVE IN PRODUCTION
 */

const posts: { id: number, title: string, summary: string, content: string, publishedAt: number }[] = [
  {
      id: 1,
      title: 'Best Clubs in Downtown Dubai',
      summary: 'Downtown Dubai is one of the most happening places in Dubai for night partying and clubbing, thanks to popular, glitzy clubs in the vicinity. Downtown Dubai’s array of party places features world-class DJs, live entertainment shows, exotic cuisines, and signature cocktails. So, if you are a fan of dancing the night away, here’s a list of the best clubs in Downtown Dubai that you can visit to make your night a memorable one.',
      content: `## Armani/Privé
      Why not witness the vibrant nightlife of Dubai from the tallest tower in the world? Located in Burj Khalifa, Armani/Privé is an iconic high-end nightclub which is an epitome of luxury, where the sultry ambience is designed by the well-known designer Giorgio Armani himself. Chill, socialize and then dance into early hours with vibrant beats of the resident and visiting international artists and DJs, while sipping on signature cocktails. Experience the signature Giorgio Armani lifestyle in the city’s most preferred after-hours destination for fast-paced fun. Though on the pricier end, this is where the most exciting nights in Dubai happen. You will also relish the food and drinks here. The club opens from 11:00 pm – 03:00 am, excluding Mondays and Wednesdays.

      ## Cavalli Club
      A stalwart on Downtown’s Best Nightclubs list, this is without a doubt one of the most famous clubs in Dubai. Designed by world-renowned designer Roberto Cavalli, the club exudes pure luxury, glamour and indulgence. The minute you step foot inside, you get the feel of extravagance infused with the style and flair of Roberto Cavalli. The club boasts everything from live entertainment to a glamorous ladies night. Within Swarovski encrusted walls and gleaming black quartz flooring, award-winning bartenders concoct signature drinks and vintages to please all palates. Thanks to a star-studded line up of international talent, from Sean Paul and Akon to Ferry Corsten and Erick Morillo, and a VIP guest list that has welcomed everyone from Will Smith to Jennifer Lopez, Cavalli Club consistently hosts the hottest nights in town.

      ## CÉ La Vi Dubai
      A MICHELIN guide restaurant, CÉ LA VI Dubai is famous for exquisite pan-Asian cuisine and world-class entertainment with stunning vistas of the Burj Khalifa and exciting rooftop parties. 54 floors high, this rooftop venue in Dubai lets you dine right beside the stunning rooftop infinity pool or groove to live entertainment with a chic cocktail in hand! Snap Instagramable pictures on the flower-framed swing dangling right in front of Burj Khalifa. Enjoy electric performances that bring the crowd to its feet and clink, sip and party the night away with spectacular views and unlimited house beverages. CÉ LA VI also features a ladies’ night for those wanting a touch of luxury as they admire the Downtown Dubai skyline. As part of the Caviar Monday’s deal, ladies can enjoy unlimited drinks between 10pm and 1am, every Monday.

      ## Inka Dubai
      Whether you wish to indulge in fusion Peruvian Cuisine in an art deco setting, or party the night away with hand-crafted cocktails, infused tonics and mocktails, including twists on classics, Inka is the ultimate place to be. The bar acts as a focal point, where guests can relax and admire the breath-taking views of Downtown Dubai from the 31st floor of the Burj Khalifa. Feeling adventurous? Explore the exotic tastes of Peru and indulge in authentic Peruvian dishes, complemented by signature drinks. With latest Timba/ Cuban salsa/ merengue/ son/ cha cha / bachata/ Reggaetone and all your favorite tracks to dance with, swing to your favorite beats with your favorite people late into the night.

      ## IRIS Dubai
      Set on the 27th floor of The Oberoi Dubai, with views of Burj Khalifa, the shimmering glass-encased space, complete with a retractable roof and a seven-meter tree serving as an Insta-worthy center piece, offers a prime alfresco spot in Meydan. IRIS includes an indoor venue for the warmer summer months. When you want to party above the Emirates, it is a renowned hot spot for memorable international DJ events, Saturday party brunches, lively ladies’ nights, and delicious cocktails. Patrons love the vibrant atmosphere, a sophisticated ambiance, an outdoor rooftop experience, sparkling city skyline views, signature sounds, and a never-ending supply of signature cocktails. Do try IRIS’s extensive menu of international meals and creative specialty fruit cocktails and mocktails.

      ## Space Club
      Space Club is redefining nightlife design in an extraterrestrial and futuristic setting that will take you on a journey to a parallel universe. Space Club is a sensational experience unlike any other, transporting you to a place far beyond your wildest imagination. Behold thrilling performances, and a unique lineup of DJs dropping the hottest beats from all around the world. Prepare to be taken on vivid journey of music, dance and thrills unlike any other. Opens Monday – Friday, 11:00 pm- 03:00 am.

      ## Club Blu
      Be prepared to be swept off your feet by an unparalleled celebration of sight, sound, scene and form at the BLU. Dubai’s hottest nightlife gem, this happening club gives you the alluring versatility of a VIP experience in one, multi-level venue. With cutting-edge areas and gracious spaces, BLU is known for the biggest parties with worldwide recognized stars, live entertainment and performances. Experience the real five-star clubbing experience with premier and up-and-coming DJs and internationally renowned artists. Thanks to its vintage spot at the 32nd floor of W Dubai, you can enjoy a breathtaking view of the city and Dubai Water Canal all the way to the Arabian Gulf. Opens daily from 21:00 till 04:00.

      ## Sounds of Tulum
      Are you looking for some exotic entertainment? Sounds of Tulum is where all the promoters, artists and brands of the underground electronic music industry worldwide gather to create a magical and paradisiacal world. Sound of Tulum is the ultimate brunch destination for music, dancing and fun times. Sounds of Tulum is a concept like no other in Downtown Dubai and is the new definition of an extravagant and luxurious lounge and restaurant. It combines modern-day entertainment, top-quality food, and high-class service.`,
      // created_at: new Date().getTime(),
      // updated_at: new Date().getTime(),
      publishedAt: new Date().getTime(),
  },
  {
      id: 2,
      title: `Fine Dining in Downtown Dubai`,
      summary: `Choosing where to eat out is an increasingly hard decision in a city jam-packed with restaurants. If you are staying in the vicinity of Downtown Dubai, we want you to be able to select the finest places that suit your every whim and preference. Here’s a review of the most premium fine dining restaurants in downtown Dubai, that offer mesmerizing views of the Burj Khalifa, delectable cuisine and impeccable service.`,
      content: `## Atmosphere
      Want to dine at the top of the world? Located at the 22nd floor of Burj Khalifa, this stunning, sky-high glass-walled restaurant offers jaw-droppingly picturesque views of Dubai, complementing an upscale ambiance and delectable palate. This chic, high-end restaurant is famous for its elegant high tea menu with sweet and savory delights, as well as an extensive array of tantalizing dishes with a vibrant mix of flavors. No matter your gastronomic preferences, you can get everything from European classics like Foie Gras Terrine and Oysters to Australian specialties such as Lamb in Tonka Jus, in addition to an indulgent dessert section. Guests can also unwind at the lounge overlooking stunning vistas of the world’s tallest performing fountains. If you are a connoisseur of fine dining, Atmosphere promises you an experience like none other.

      ## Zuma
      Flawless modern Japanese with eccentricity, flair, style and substance, Zuma has ostensibly become synonymous with fine Japanese cuisine in Dubai. Located at the heart of the city, in the vicinity of Burj Khalifa, Zuma is home to the Izakaya style of dining, serving authentic Japanese Cuisine. What makes Zuma a roaring success is that they take the technique and study associated with Japanese food and blends it with glitz and glamour from the West. If you are planning a trip to Zuma, don’t forget to try the rib eye with wafu sauce and garlic chips, as well as the Instagram-able Miso-marinated black cod wrapped in hoba leaf and the Tsubu-miso gake hinadori no oven yaki. In addition to the main dining area, patrons can head over to the expertly manned Sushi and Robata counters.

      ## Thiptara
      A sophisticated and intimate space, Thiptara serves traditional Royal Thai cuisine with an emphasis on Bangkok-style seafood. Literally translating to ‘magic at the water’, the restaurant offers enchanting dining experiences, surrounded by majestic banyan trees and lush tropical gardens by the riverside. A feast for the senses, the legendary Thai lifestyle of days gone by reflects in Thiptara, not only through its elegant décor but also in its cuisine. Feast on authentic recipes, with an extra punch of flavor as the kitchen manages to add a little something extra to all the classics, making it a meal to remember. Choose from a selection of curries including beef Panang, spicy roast red duck and green chicken, or t exquisite Bangkok-style seafood dishes, including fried sea bass, stir-fried lobster and sea bream, paired with popular plates like pad Thai, tom yum soup and zesty salads, while being entertained by the water show.

      ## Sucre
      We cannot thank Chef Fernando Trocca enough for introducing Latin American open-fire cooking in Dubai with a touch of European influence. If you want to experience food like never before, you’re guaranteed a lively night out at this fashionable spot with its huge open kitchen and buzzy bar. Indubitably, Sucre also boasts an extensive collection of the world’s finest grapes for wine connoisseurs. While the menu is extensive, we recommend that you try king crab tostada, Argentinian bone-in ribeye and squid ink paella.

      ## Armani
      If you are a connoisseur of the finest food and superior wines, there is no better place than the Michelin-starred Armani Ristorante. The restaurant offers classic Italian cuisines with premium selections such as Agnolotti del plin, filetto di scorfano, Risotto Tartufo and several starters. Aside from meat-based dishes, Ristorante also offers some beautiful seafood dishes. This sophisticated, opulent restaurant comes with high ceilings, well-spaced tables, marble flooring and a large, central glass-fronted kitchen where diners can watch the chefs hard at work. Dine outside against the backdrop of the iconic Dubai Fountain and indulge in modern Italian fares leveraging first-class ingredients in beautifully presented, rich dishes full of color, flavor and textural contrasts. From fully tailored service to a degustation-style menu and recommendations from an in-house sommelier, this restaurant has all that it takes.

      ## Neos
      Perched on the 63rd floor of Address Downtown, offering incredible views of the glittering city skyline, Neos is the ultimate hub for the city’s distinguished and elite. This luxurious sky lounge offers a heightened experience for those seeking relaxation and pre-dinner snacks and beverages. The best thing about Neos is that it offers an unobstructed view of the Burj Khalifa, while the Dubai Fountain show will dazzle you throughout the evening with its record-breaking aquatic choreography. Sample a wide array of freshly prepared snacks that include a decadent cheese platter and oysters along with more filling foods such as braised beef ribs and chicken shawarma, while sipping on a Titan Martini. Don’t forget to end the evening on a sweet note with a dessert such as a delectable chocolate mousse or fruit salad. This is without a doubt the ultimate place to experience a symphony of sights, tastes and sounds that, quite simply, make you feel on top of the world, amidst avant-garde interiors.

      ## Bagatelle
      Counted among the top restaurants in the city, Bagatelle Dubai welcomes culinary aficionados from all over the world to experience the ultimate joie de vivre lifestyle. If you are looking to kick off your night with a good meal, Bagatelle is the perfect place to enjoy a late-night French-Mediterranean quality dining experience, reminiscent of the epicurean spirit of the South of France. We recommend booking a table no earlier than 10pm to get the full Bagatelle experience, including a menu of standout French dishes, live music and plenty of dancing on tables. Opulent and chic, Bagatelle reflects classic Parisian elements highlighted by bold artwork and pulsating music, keeping guests entertained and mesmerized every night.

      ## Trèsind
      A multi–Time Out Dubai Best Indian award winner, Trèsind is the birthplace of “innovative Indian cuisine”, With the aim to foster the revered legacy of Indian food. Don’t come here expecting a simple Indian fare – instead, revel in the signature Indian dishes that come served alongside plenty of dry ice, foams, gels and other theatrics that taste as good as they look. dining at Trèsind is a once-in-a-lifetime gastronomic experience that celebrates the evolution of contemporary Indian cuisine.`,
      publishedAt: new Date().getTime(),
  },
  {
      id: 3,
      title: `PAMPER YOURSELF WITH THE BEST SPAS IN DOWNTOWN DUBAI`,
      summary: `Wish to escape the hustle and bustle of the teeming city life? Want to relax? Indulge? Be totally pampered and spoiled? If you want to experience over-the-top luxury, a day spent in a spa will have you feeling refreshed and rejuvenated from inside out. If you are staying in Downtown Dubai, here are the most extravagant temples of relaxation to check out.`,
      content: `## Sofitel Spa
      Step into an oasis of calm and tranquility within Downtown Dubai and immerse yourself in luxurious retreat experiences inside the Sofitel spa. Located at the second floor of the Hotel, the Sofitel spa features 8 treatment rooms, a couples treatment room, dry sauna, steam room and hammam facilities. Experience a rejuvenating and relaxing day at Sofitel Spa and rejuvenate your senses with world’s best massages, medically inspired facials, smoothing scrubs, thermal shoulder treatments, Turkish and Moroccan hammam, and the ultimate 3-teas purifying body wrap that will leave you feeling refreshed.

      ## Saray Spa
      Inspired by the glories of the Ottoman Empire and Middle Eastern royalty, the Saray Spa offers a resplendent therapeutic experience. Saray Spa offers a personal experience of restoration and renewal through ancient regional healing techniques and rituals that have withstood the test of time, using only locally-sourced, organic ingredients. Spanning the entire third floor of both towers at JW Marriott Marquis Dubai, explore an indulgent selection of spa experiences in one of 17 treatment rooms, relaxing Hammams, Jacuzzis, steam rooms, saunas, additional hydro-facilities and spacious relaxation areas. Saray spa is the most popular haven of relaxation for both holidaymakers and locals, while still staying true to the old Arab customs of hospitality.

      ## The Spa
      An oasis of tranquility, the Spa at Palace Downtown lets you delve in rejuvenating treatments, world-class facilities and stunning views of Dubai. Exuding elegance and muted earth tones, amidst inviting furnishings and Arabesque patterns, the Spa is the ultimate retreat for those seeking a relaxing environment to rejuvenate and refresh their mind and body. Located at the regal Palace Downtown, the spa is fit for royalty, featuring everything from an oriental bathhouse with a hammam slab to Jacuzzis, monsoon showers, steam rooms, consultation spaces, relaxation lounges and a well-equipped 24-hour fitness center. Enjoy therapies from all around the world, such as Thai, Balinese, Filipino, Singaporean, Swedish, French and Polynesian. If you are looking to spend a day at the Spa, try the signature one desert journey, including a body scrub with desert sand and salt, followed by a refreshing Moroccan mint oil herbal massage.

      ## Armani Spa
      Enjoy the serene and blissful atmosphere of the Armani/SPA, offering unique treatments and exclusive services designed to help you fully unwind and regenerate. Located at Armani Hotel Dubai, the spa boasts a sleek and sophisticated atmosphere, reflecting the classic Armani lifestyle and design philosophy, designed to help you calm your senses. Take a dip in the enchanting relaxation pool, while enjoying unobstructed views of the city, or get involved in the spa trail with saunas, steam baths, and ice waterfall, for a day of relaxation and sheer indulgence. Finish off the day by sipping hot teas, cold infusions, and fresh fruits to boost your energy to better face your day. The best part is that each guest at the Armani SPA receives a personal consultation from a spa professional to develop a bespoke sensory experience designed by Armani.

      ## The Ritz Carlton Spa
      The Ritz-Carlton Spa, DIFC, is a haven for indulgent body treatments. Head over to the Ritz Carlton if you wish to pamper yourself and experience six 60-minute full body massages, while enjoying complimentary access to the spa, swimming pool, and gym facilities. Utilizing traditions and ingredients that date back eons, the Ritz Carlton spa clears the path for holistic wellbeing. From world-class massages to facials and body therapies inspired by the sea, each treatment uses techniques and ingredients from Dubai, along with India, Bali, Morocco and Mexico. The spa features 12 treatments rooms, tranquility lounges, eucalyptus-infused steam-rooms, an outdoor relaxation pool, hot and cold plunge pools and a state-of-the-art fitness center for ultimately luxurious pampering. Don’t forget to try the chardonnay luxury ritual, A full body exfoliation with chardonnay grape seeds combined with ultrasound technology, that leaves the skin glowing, refreshed and toned. Or the specialty ‘East meets West’ body massage that combines techniques from Eastern and Western trained therapists.

      ## Jiva Spa
      The award-winning and all-natural Jiva Spa personifies the heart of Indian culture with its calming look embellished by lotus flower motifs embossed on the stone floors, warm tones and natural fabrics, and especially the garland of fresh flowers that guests are greeted with upon arrival. Enjoy a vast array of spa treatments and rituals that blend some classic Indian healing techniques with the finest natural ingredients and the iconic Taj service. Located within the Taj Dubai at the Burj Khalifa Boulevard, this mesmerizing wellness oasis only utilizes the most premium natural ingredients, herbs and essential oils in all its preparations. Don’t forget to try one of the aroma therapies, treat yourself to a body scrub and wrap that will leave you feeling refreshed and recharged, or ask for a soothing yoga session and watch your worries and stressors floating away.`,
      publishedAt: new Date().getTime(),
  },
  {
      id: 4,
      title: `Explore Downtown Dubai places to visit`,
      summary: `Called “The Centre of Now”, Downtown Dubai offers an unparalleled lifestyle appeal to both residents and visitors with a wide array of shopping options, culinary delights from around the world, hosts of world-class attractions, upscale hotels, and chic leisure points, and is home to some of the city’s largest festivities and an eccentric nightlife. Without a doubt, staying in Downtown Dubai puts you smack dab in the city’s vortex of vibrancy. If you are planning to stay in this seamlessly connected multi-purpose neighborhood, here are the most popular destinations to add to your bucket list.`,
      content: `## Burj al Khalifa
      Towering at a height of 2,700 feet, this awe-inspiring global icon seems just short of touching the skies. With two observation decks, a Las Vegas-inspired fountain, some of the world’s most luxurious hotels and multiple restaurants, this 21st-century wonder would leave you gaping in amazement. A high-speed elevator whips you up to the observation deck on the 124th floor where floor-to-ceiling windows offer a magnificent unobstructed view of the city, the desert and the Persian Gulf. If you want to go even higher, soar all the way up to the 148th floor “at the top of the sky” and enjoy a VIP tour with refreshments. An interactive screen here lets you “fly” to different city landmarks by hovering your hands over high-tech sensors. If you’re feeling peckish, the highly respected Armani restaurant boasts an extensive selection of delights that are sure to leave you satisfied.

      ## Dubai Opera
      Located in Downtown Dubai, Dubai Opera is the radiant center of culture and arts in Dubai. The 2000-seat multi-format theatre is the ultimate hub for authentic, creative and engaging performing arts and world-class entertainment productions. If you want to witness world-class talent, from opera, ballet and classical music concerts to musical theatre, fashion shows, jazz, comedy, family shows and a full range of live entertainment, head on to the dhow shaped architectural wonder and treat yourself to a spectacular show. This will be one of the most luxurious things to do in Downtown Dubai on your bucket list. If you feel hungry afterwards, head up to the rooftop restaurant and enjoy a spectacular dinner with views of the Burj Khalifa.

      ## Dubai Mall
      Found in the very epicenter of Downtown Dubai, witness the world’s largest destination for entertainment, leisure and retail. The Dubai mall is home to some 1,500 retail, food and drink outlets, a humungous walk-through aquarium, a world-class ice rink, an underwater Zoo, a 76,000-square foot VR themed amusement park, 14,000 parking spaces and tons of exciting experiences for visitors. Dubai Mall pays homage to high fashion with more than 70 signature stores, including Fashion Avenue, Galeries Lafayette, France’s leading lifestyle retailer and Bloomingdale’s, America’s leading department store. After a day of shopping spree, shoppers will love to glide over the ice-cold chilled surface of the giant Olympic sized ice rink or head over to the aquarium where 10 million liters of water hold some of the most charismatic jewels of aquatic life.

      ## Sconci Art Gallery
      A paradise for art enthusiasts in need of inspiration, the Sconci Art Gallery exhibits some of the most obscure masterpieces from the seventeenth century to the present day. This is one place where you can appreciate the works of both 17th century artists, such as Carlo Morganti and Antonio Corpora, to modern and contemporary art of the 21st century. The best part is that each work you see here is accompanied by an expertise or a certificate of authenticity which means it is legally registered in the archive of the artist. If you want to see the world of art unfurl before your eyes, be sure to visit exhibitions that showcase artist-specific pieces or feature art from different parts of the world.

      ## Dubai Fountain
      Indulge yourself in the world’s largest choreographed show of water, music and light at the dancing fountain show. Every 30 minutes, starting 6 p.m., jets of illuminated water undulate as gracefully as a belly dancer, arc like a dolphin and soar up to heights of 500 ft, in perfect coordination with classical, Arabic and international contemporary music. Set against the backdrop of the glittering Burj Khalifa, the breathtaking display is a must-see on your list. There are plenty of great vantage points where you can get front-row tickets to this wonder, such as the restaurants at Souk Al Bahar, the bridge linking Souk Al Bahar with Dubai Mall, the Dubai Mall waterfront terrace or aboard a 272m-long floating boardwalk (Dhs20), which takes you just 9m away from the fountain.

      ## Calabar Lounge
      Vibrant, Latin-inspired Calabar is a premium lounge bar, attracting Dubai’s fashionable and elite. As the sun sets behind the Burj Khalifa, Calabar’s sundowner terrace comes alive with an energetic buzz. The menu features a heady mix of savory South American specialties with refreshing beverages and exotic cocktails. This premium lounge is the perfect place to throw a party or simply to witness the vibrant nightlife of Dubai.

      ## Museum of the Future
      Designed as an asymmetric Torus clad in calligraphy-engraved steel and glass, the museum of the future focuses on harnessing the lessons from our present day to construct the future. The Museum of the Future combines elements of exhibition, immersive theatre and themed attraction, inviting you to look beyond the present to the possible. Through VR and AR, big data analysis, AI, and human machine interaction installations and displays, the first 3 floors focus on the possible futures of outer space resource development, ecosystems and bioengineering, while another floor will showcase near-future technologies that will transform our world by addressing challenges in areas such as health, water, food, transportation and energy. The final floor will be dedicated for children, where they can explore and think through solutions to the climate crisis.`,
      publishedAt: new Date().getTime(),
  },
  {
      id: 5,
      title: `Kids-Friendly places Downtown Dubai`,
      summary: `While Downtown Dubai is usually synonymous with the iconic, and record-breaking Burj Khalifa as well as a glamorous nightlife and high-end dining, there are many family-friendly attractions to look forward to in the Downtown area if you are traveling with kids. From an exotic underwater life to rollercoasters and VR zombies and waddling penguins, here are Dubai’s best kid-approved activities.`,
      content: `## Dubai Aquarium and Underwater Zoo
      Want to explore one of the largest and most stunning aquariums in the world? Especially if you are traveling with kids, you wouldn’t want to miss out on the massive 10-million-liter tank at the Dubai Aquarium and Underwater Zoo, which is home to over than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere. Stroll through a 48-metre tunnel, with the aquarium enveloping you from overhead and around, and enjoy a fish-eye view, with sand tiger sharks and stingrays swimming overhead. Located at The Dubai Mall, Dubai Aquarium & Underwater Zoo is one of the most captivating attractions in Dubai. Located just above the aquarium, Underwater Zoo brings visitors up close with penguins, King croc, piranhas, crabs, water rats, sea horses, jellyfish and plenty more. If you want more, hop into the Glass Bottom Boat to drift over the water surface and observe various creatures swimming below, get wet in a snorkeling cage, and even go swimming with the sharks inside the tank.

      ## IMG Worlds of Adventure
      If you are staying in Downtown Dubai, don’t forget to visit the world’s largest indoor theme park full of thrilling rides, international pop culture icons, and much more. The 1.5 million square feet playground is divided into four epic adventure zones: Marvel, Cartoon Network, IMG Boulevard, and The Lost Valley, in addition to 22 adrenaline-fueled rides on offer. Your kids will love to join their favorite superheroes on action-packed thrill rides and test their courage at the Haunted Hotel. If your little one is obsessed with dinosaurs, take them to see the prehistoric world of dinosaurs at The Lost Valley, where rides like the velociraptor and the predator await. In addition, there are numerous themed retail stores and dining venues, as well as a 12-screen Novo cinema complex with a fantastic selection of blockbusters. Bonus: kids love meet and greet opportunities with superstars such as Spider-Man, Thor and The Powerpuff Girls.

      ## Kidzania
      KidZania is an award-winning children’s ‘edutainment’ concept, located on Level 2 of The Dubai Mall. It packs more than 40 role-playing activities for children aged 2-16, where they’ll learn all about jobs, money and developing real-world life skills outside of a classroom setting. With so many professions to choose from, including dentistry, aviation, fashion, and construction, your little ones will have a field’s day ‘adulting’ in an interactive child-sized city, featuring universities, banks, hospitals and more; all under the supervision of adult “Zupervisors”. Your kids can even create bank accounts, get passports, and even earn their own KidZos (KidZania’s currency), which they get to spend when cooking, painting, driving or going to the spa. Kids and adults alike enjoy entering the world of KidZania, where the children are in charge! Inspire your children to follow their dreams and get ready for a better world by taking them to kidzania.

      ## Play DBX
      Play DXB offers a complete family entertainment concept with state-of-the-art VR attractions, rides, soft play, video games and roller coaster inside an indoor amusement park in The Dubai Mall. Experience the best of augmented and virtual reality, and even get to feel the thrill of the fantastic Burj Drop experience, where you’ll propel down the side of the record-breaking Burj Khalifa. Teens and adults alike gravitate towards The Walking Dead Outbreak VR game, where you have to survive a zombie attack. While the little ones are having a whale of a time at the inflatable playground and trampolines, you can don an Oculus gaming headset, delve into a Transformers-themed adventure and beat the bad guys. You and your little ones will live unforgettable and mind-blowing experiences wholly immersive rides, interactive games and educational journeys.

      ## Mirror Maze
      Are you and your little ones up for a challenge? Grab your child and get ready to find your way through a mind-bending maze of mirrors that will challenge your sense of sight. Inside this mind-boggling, dizzying labyrinth, you need to find your way through a disorienting maze of mirrors! Get ready for some tricky optical illusions and lots of giggles from your kids. Once within the maze, you won’t be able to work out which way to go and will have to use your senses of touch and adventure to work out the way. Embark on this adventure as a family and spend some quality time together, only in Dubai Mall!

      ## Ski Dubai
      Are you looking to experience the thrill of winters in Downtown Dubai? Strap on your snow boots and take your kids to Ski Dubai, an indoor ski resort with 22,500 square meters of the indoor ski area. Located in the Mall of the Emirates. this gigantic indoor ski resort is the perfect place to ride a traditional toboggan down the snow hills or zoom down the twin-track bobsled, enjoy immersive experiences inside a snow cavern or polish your snowballing skills. Take your kids on an exhilarating ride on the Giant Ball or hop aboard the chairlift for a one-of-a-kind bird’s eye view of the entire park. Your kids will especially love to meet and play with Ski Dubai’s newest residents; the Snow Penguins. If your kids are interested in learning how to ski, a day or two of private lessons will do the trick. After a fun packed day in the snow, warm up with a cup of hot chocolate at Ski Dubai’s winter-themed Avalanche and Ice Café.`,
      publishedAt: new Date().getTime(),
  }
];


export default async (strapi) => {
  for (const post of posts) {
    // Find the BlogPost by id
    const entry = await strapi.entityService.findOne('api::blog-post.blog-post', post.id);
    // Create it if it doesn't exist
    if (!entry) {
      const newEntry = await strapi.entityService.create('api::blog-post.blog-post', {
        data: {
          ...post
        }
      });
    }
  }
};
